name: Publish Package

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  publish:
    name: "Publish to npmjs.com"
    runs-on: ubuntu-latest
    if: github.repository == 'lanekassen/portal-komponenter'
    permissions:
      id-token: write # Required for OIDC
      contents: write # to check out repo (actions/checkout) and commit version changes (changesets/action/version)
      pull-requests: write # to create pull request (changesets/action/version)
    concurrency:
      group: release-npm-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # 6.0.8
        with:
          cache: true

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          # never use caching in release builds
          package-manager-cache: false

      - name: Install
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-script: pnpm publish-packages
          version-script: pnpm version-packages
          commit-message: "chore: new release"
          pr-title: "chore: new release"
          create-github-releases: true
        env:
          # Trenger å eksplisitt sette denne til en tom streng for å bruke Trusted Publishing
          # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
          NPM_TOKEN: ""